// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1r6hkOxy-h5Ij-_V8C_aEjjkHoTXjZA0',
    appId: '1:354816162776:web:cad4ef4a1392b76cb7d0ad',
    messagingSenderId: '354816162776',
    projectId: 'my-planner-vol-2',
    authDomain: 'my-planner-vol-2.firebaseapp.com',
    storageBucket: 'my-planner-vol-2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA82Bze8kp7h9wYCEESSsbWuH4E_G8Jfec',
    appId: '1:354816162776:android:189cfa7f43b97f9fb7d0ad',
    messagingSenderId: '354816162776',
    projectId: 'my-planner-vol-2',
    storageBucket: 'my-planner-vol-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqXuxyNawhlSeo9Cm6ab2Tzt0aNjvDztY',
    appId: '1:354816162776:ios:2edd631880982346b7d0ad',
    messagingSenderId: '354816162776',
    projectId: 'my-planner-vol-2',
    storageBucket: 'my-planner-vol-2.appspot.com',
    iosClientId:
        '354816162776-v42v9hck7qq367fam5bjir0phc46qtr3.apps.googleusercontent.com',
    iosBundleId: 'com.martynafidler.myPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqXuxyNawhlSeo9Cm6ab2Tzt0aNjvDztY',
    appId: '1:354816162776:ios:2edd631880982346b7d0ad',
    messagingSenderId: '354816162776',
    projectId: 'my-planner-vol-2',
    storageBucket: 'my-planner-vol-2.appspot.com',
    iosClientId:
        '354816162776-v42v9hck7qq367fam5bjir0phc46qtr3.apps.googleusercontent.com',
    iosBundleId: 'com.martynafidler.myPlanner',
  );
}
